import { Student, User, SchoolClass, Trip, NotificationItem, CerfaSanitarySheet } from './types';

export const INITIAL_USERS: User[] = [
  {
    id: 'user-parent-1',
    name: 'Claire DUPONT',
    firstName: 'Claire',
    lastName: 'DUPONT',
    email: 'famille.dupont@email.fr',
    role: 'parent',
    phone: '06 12 34 56 78',
    password: 'parent123',
    secretQuestion: 'Quel est le nom de jeune fille de votre mère ?',
    secretAnswer: 'Martin',
    isDemo: true,
  },
  {
    id: 'user-organizer-1',
    name: 'Thomas VASSEUR',
    firstName: 'Thomas',
    lastName: 'VASSEUR',
    email: 't.vasseur@ac-paris.fr',
    role: 'organizer',
    phone: '06 98 76 54 32',
    assignedTripIds: ['trip-1'],
    password: 'prof123',
    secretQuestion: 'Quel était le nom de votre premier animal de compagnie ?',
    secretAnswer: 'Rex',
    isDemo: true,
  },
  {
    id: 'user-admin-1',
    name: 'Alexandre CHEN',
    firstName: 'Alexandre',
    lastName: 'CHEN',
    email: 'admin.sanitaire@jeanmoulin.fr',
    role: 'admin',
    phone: '01 45 67 89 00',
    password: 'admin123',
    secretQuestion: 'Dans quelle ville êtes-vous né(e) ?',
    secretAnswer: 'Lyon',
    isDemo: true,
  },
];

export const INITIAL_CLASSES: SchoolClass[] = [
  { id: 'c-6a', name: '6e A', level: '6e', studentCount: 28, mainTeacher: 'Mme Lambert' },
  { id: 'c-6b', name: '6e B', level: '6e', studentCount: 29, mainTeacher: 'M. Vasseur' },
  { id: 'c-5c', name: '5e C', level: '5e', studentCount: 30, mainTeacher: 'Mme Bernard' },
  { id: 'c-4a', name: '4e A', level: '4e', studentCount: 27, mainTeacher: 'M. Garcia' },
  { id: 'c-3b', name: '3e B', level: '3e', studentCount: 28, mainTeacher: 'Mme Mercier' },
  { id: 'c-cm2', name: 'CM2', level: 'CM2', studentCount: 25, mainTeacher: 'M. Petit' },
];

export const INITIAL_TRIPS: Trip[] = [
  {
    id: 'trip-1',
    name: 'Voyage Angleterre 2027',
    destination: 'Londres, Oxford & Windsor (Royaume-Uni)',
    startDate: '2027-03-15',
    endDate: '2027-03-21',
    eligibleClasses: ['6e A', '6e B', '4e A'],
    organizerId: 'user-organizer-1',
    organizerName: 'Thomas VASSEUR',
    maxStudents: 150,
    description: 'Séjour d immersion linguistique et culturelle en familles hôtesses. Visite de musées nationaux, universités et sites historiques.',
    status: 'ouvert',
  },
  {
    id: 'trip-2',
    name: 'Classe de Neige & Sciences - Grand Bornand 2027',
    destination: 'Le Grand-Bornand (Haute-Savoie)',
    startDate: '2027-01-20',
    endDate: '2027-01-26',
    eligibleClasses: ['5e C', '3e B'],
    organizerId: 'user-organizer-2',
    organizerName: 'Sophie BERNARD',
    maxStudents: 60,
    description: 'Pratique du ski alpin et de fond, étude de l écosystème alpin et nivologie.',
    status: 'ouvert',
  },
  {
    id: 'trip-3',
    name: 'Échange Culturel Barcelone 2027',
    destination: 'Barcelone (Espagne)',
    startDate: '2027-05-10',
    endDate: '2027-05-16',
    eligibleClasses: ['4e A', '3e B'],
    organizerId: 'user-organizer-3',
    organizerName: 'Laurent GARCIA',
    maxStudents: 50,
    description: 'Découverte du patrimoine catalan et échanges avec le collège partenaire Joan Miró.',
    status: 'ouvert',
  },
];

export function createEmptyCerfa(identity: {
  lastName: string;
  firstName: string;
  birthDate: string;
  gender: 'Garcon' | 'Fille';
}): CerfaSanitarySheet {
  return {
    identity: {
      lastName: identity.lastName.toUpperCase(),
      firstName: identity.firstName,
      birthDate: identity.birthDate,
      gender: identity.gender,
      childMobilePhone: '',
      socialSecurityNumber: '',
    },
    vaccinations: {
      obligatoires: {
        diphterie: { done: null, lastBoosterDate: '' },
        tetanos: { done: null, lastBoosterDate: '' },
        poliomyelite: { done: null, lastBoosterDate: '' },
        dtPolio: { done: null, lastBoosterDate: '' },
        tetracoq: { done: null, lastBoosterDate: '' },
      },
      hasContraindication: false,
      contraindicationDetails: '',
      recommandes: {
        bcg: { done: false, date: '' },
        hepatiteB: { done: false, date: '' },
        ror: { done: false, date: '' },
        coqueluche: { done: false, date: '' },
        autres: { done: false, date: '', name: '' },
      },
    },
    medicalInfo: {
      hasMedicalTreatment: false,
      treatmentDetails: '',
      hasPrescriptionAttached: false,
      hasPai: false,
      antecedents: {
        rubeole: false,
        varicelle: false,
        angines: false,
        rhumatismes: false,
        scarlatine: false,
        coqueluche: false,
        otites: false,
        asthme: false,
        rougeole: false,
        oreillons: false,
      },
      allergies: {
        asthme: false,
        medicamenteuses: false,
        alimentaires: false,
        autres: '',
      },
      allergyCauseAndAction: '',
      isSelfMedicationReported: false,
      healthDifficulties: '',
    },
    parentRecommendations: '',
    structuredDiet: {
      category: 'standard',
      details: '',
    },
    treatingDoctor: {
      name: '',
      phone: '',
    },
    legalGuardian: {
      fullName: '',
      relationship: '',
      address: '',
      homePhone: '',
      workPhone: '',
      mobilePhone: '',
      email: '',
    },
    declarationAccepted: false,
    signature: {
      signedByName: '',
      signedDate: '',
      signatureDataUrl: '',
      validatedAt: '',
      version: 0,
    },
    documents: [],
    history: [],
    versions: [],
  };
}

export const INITIAL_STUDENTS: Student[] = [
  {
    id: 'stu-paul-dupont',
    parentId: 'user-parent-1',
    schoolEstablishment: 'Collège & Lycée Jean Moulin - Académie de Paris',
    schoolClass: '6e B',
    schoolLevel: '6e',
    internalId: 'JM-2026-6B-014',
    schoolYear: '2026-2027',
    boardingStatus: 'DP',
    completenessPercent: 0,
    status: 'incomplete',
    registeredTripIds: [],
    createdAt: '2026-09-01T09:00:00Z',
    updatedAt: '2026-09-01T09:00:00Z',
    cerfa: createEmptyCerfa({
      lastName: 'DUPONT',
      firstName: 'Paul',
      birthDate: '2015-04-12',
      gender: 'Garcon',
    }),
  },
  {
    id: 'stu-emma-dupont',
    parentId: 'user-parent-1',
    schoolEstablishment: 'Collège & Lycée Jean Moulin - Académie de Paris',
    schoolClass: '4e A',
    schoolLevel: '4e',
    internalId: 'JM-2026-4A-032',
    schoolYear: '2026-2027',
    boardingStatus: 'DP',
    completenessPercent: 0,
    status: 'incomplete',
    registeredTripIds: [],
    createdAt: '2026-09-02T10:15:00Z',
    updatedAt: '2026-09-02T10:15:00Z',
    cerfa: createEmptyCerfa({
      lastName: 'DUPONT',
      firstName: 'Emma',
      birthDate: '2013-09-24',
      gender: 'Fille',
    }),
  },
  {
    id: 'stu-lucas-dupont',
    parentId: 'user-parent-1',
    schoolEstablishment: 'École Primaire d Application Jean Moulin',
    schoolClass: 'CM2',
    schoolLevel: 'CM2',
    internalId: 'JM-2026-CM2-022',
    schoolYear: '2026-2027',
    boardingStatus: 'Externe',
    completenessPercent: 0,
    status: 'incomplete',
    registeredTripIds: [],
    createdAt: '2026-09-03T16:00:00Z',
    updatedAt: '2026-09-03T16:00:00Z',
    cerfa: createEmptyCerfa({
      lastName: 'DUPONT',
      firstName: 'Lucas',
      birthDate: '2016-11-05',
      gender: 'Garcon',
    }),
  },
  {
    id: 'stu-lucas-martin',
    parentId: 'user-parent-2',
    schoolEstablishment: 'Collège & Lycée Jean Moulin',
    schoolClass: '5e C',
    schoolLevel: '5e',
    internalId: 'JM-2026-5C-008',
    schoolYear: '2026-2027',
    boardingStatus: 'Externe',
    completenessPercent: 0,
    status: 'incomplete',
    registeredTripIds: [],
    createdAt: '2026-09-04T11:00:00Z',
    updatedAt: '2026-09-04T11:00:00Z',
    cerfa: createEmptyCerfa({
      lastName: 'MARTIN',
      firstName: 'Lucas',
      birthDate: '2014-07-03',
      gender: 'Garcon',
    }),
  },
  {
    id: 'stu-sarah-lefebvre',
    parentId: 'user-parent-3',
    schoolEstablishment: 'Collège & Lycée Jean Moulin',
    schoolClass: '6e B',
    schoolLevel: '6e',
    internalId: 'JM-2026-6B-028',
    schoolYear: '2026-2027',
    boardingStatus: 'DP',
    completenessPercent: 0,
    status: 'incomplete',
    registeredTripIds: [],
    createdAt: '2026-09-05T08:30:00Z',
    updatedAt: '2026-09-05T08:30:00Z',
    cerfa: createEmptyCerfa({
      lastName: 'LEFEBVRE',
      firstName: 'Sarah',
      birthDate: '2015-01-18',
      gender: 'Fille',
    }),
  },
  {
    id: 'stu-noah-benali',
    parentId: 'user-parent-4',
    schoolEstablishment: 'Collège & Lycée Jean Moulin',
    schoolClass: '5e C',
    schoolLevel: '5e',
    internalId: 'JM-2026-5C-019',
    schoolYear: '2026-2027',
    boardingStatus: 'DP',
    completenessPercent: 0,
    status: 'incomplete',
    registeredTripIds: [],
    createdAt: '2026-09-05T14:45:00Z',
    updatedAt: '2026-09-05T14:45:00Z',
    cerfa: createEmptyCerfa({
      lastName: 'BENALI',
      firstName: 'Noah',
      birthDate: '2014-11-29',
      gender: 'Garcon',
    }),
  },
  {
    id: 'stu-chloe-dubois',
    parentId: 'user-parent-5',
    schoolEstablishment: 'Collège & Lycée Jean Moulin',
    schoolClass: '4e A',
    schoolLevel: '4e',
    internalId: 'JM-2026-4A-007',
    schoolYear: '2026-2027',
    boardingStatus: 'DP',
    completenessPercent: 0,
    status: 'incomplete',
    registeredTripIds: [],
    createdAt: '2026-09-06T09:10:00Z',
    updatedAt: '2026-09-06T09:10:00Z',
    cerfa: createEmptyCerfa({
      lastName: 'DUBOIS',
      firstName: 'Chloé',
      birthDate: '2013-03-14',
      gender: 'Fille',
    }),
  },
  {
    id: 'stu-arthur-roussel',
    parentId: 'user-parent-6',
    schoolEstablishment: 'Collège & Lycée Jean Moulin',
    schoolClass: '6e B',
    schoolLevel: '6e',
    internalId: 'JM-2026-6B-005',
    schoolYear: '2026-2027',
    boardingStatus: 'Interne',
    completenessPercent: 0,
    status: 'incomplete',
    registeredTripIds: [],
    createdAt: '2026-09-07T16:20:00Z',
    updatedAt: '2026-09-07T16:20:00Z',
    cerfa: createEmptyCerfa({
      lastName: 'ROUSSEL',
      firstName: 'Arthur',
      birthDate: '2015-08-22',
      gender: 'Garcon',
    }),
  },
  {
    id: 'stu-lea-moreau',
    parentId: 'user-parent-7',
    schoolEstablishment: 'Collège & Lycée Jean Moulin',
    schoolClass: '5e C',
    schoolLevel: '5e',
    internalId: 'JM-2026-5C-024',
    schoolYear: '2026-2027',
    boardingStatus: 'DP',
    completenessPercent: 0,
    status: 'incomplete',
    registeredTripIds: [],
    createdAt: '2026-09-08T10:00:00Z',
    updatedAt: '2026-09-08T10:00:00Z',
    cerfa: createEmptyCerfa({
      lastName: 'MOREAU',
      firstName: 'Léa',
      birthDate: '2014-05-19',
      gender: 'Fille',
    }),
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    targetRole: 'parent',
    targetUserId: 'user-parent-1',
    title: 'Fiche sanitaire à renseigner',
    message: 'Veuillez renseigner et signer la fiche sanitaire CERFA pour vos enfants.',
    date: '2026-09-11T08:20:00Z',
    read: false,
    type: 'warning',
  },
  {
    id: 'notif-2',
    targetRole: 'parent',
    targetUserId: 'user-parent-1',
    title: 'Voyages scolaires 2026-2027 ouverts',
    message: 'Les inscriptions aux voyages scolaires sont ouvertes. Vous pouvez choisir un voyage pour chaque enfant.',
    date: '2026-09-10T18:35:00Z',
    read: true,
    type: 'info',
  },
  {
    id: 'notif-3',
    targetRole: 'organizer',
    title: 'Campagne de fiches sanitaires',
    message: 'Suivi des fiches sanitaires des élèves en cours pour les prochains séjours.',
    date: '2026-09-08T11:10:00Z',
    read: false,
    type: 'alert',
  },
  {
    id: 'notif-4',
    targetRole: 'admin',
    title: 'Rappel campagne fiches sanitaires 2026-2027',
    message: 'Suivi de la complétude des fiches sanitaires de l établissement en cours.',
    date: '2026-09-11T07:00:00Z',
    read: false,
    type: 'info',
  },
];
